services:
  - type: web
    name: task-manager-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromSecret: true
      - key: JWT_SECRET
        fromSecret: true
      - key: FRONTEND_URL
        # value: https://your-frontend-domain.vercel.app
